services:
  - type: web
    name: discord-bot
    env: docker
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y wget gnupg unzip

      # Install Chrome
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      
      # Get Chrome version and install matching ChromeDriver
      CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
      CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%%.*}")
      wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python botforserver.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CHROME_BINARY
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: RENDER
        value: "true"